version: 2
updates:
  - package-ecosystem: "gradle"
    open-pull-requests-limit: 3
    directory: "/"
    schedule:
      interval: "daily"
    default_labels:
      - "bot: updated dependencies"
    reviewers:
      - "woocommerce/android-developers"
    ignore:
      # The Android Gradle Plugin is a dependency we'd like to have in sync with other
      # in-house libraries due to compatibility with composite build.
      - dependency-name: "com.android.tools.build:gradle"
